### ISSUE TITLE
so slow

### ISSUE THREAD

**Issue by iardanothing** [eternalfrenzy/discord-animated-status#1]
i want to make it more faster but it doesnt change

**Comment by eternalfrenzy** [comment]
if you mean the delay between status changes, the minimum and recommended delay is 3 seconds, not lower. if it's gonna be lower, discord can rate-limit you because of requests overflow, and discord animated status avoids that.
![image](https://user-images.githubusercontent.com/52493771/73544270-e136fc80-4449-11ea-9062-8b887171401b.png)
